# Generated by Django 3.0.5 on 2020-11-15 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyModelDtls',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=100)),
                ('company_name', models.CharField(max_length=250)),
                ('country', models.CharField(max_length=100)),
                ('model_name', models.CharField(max_length=100)),
                ('file_path', models.CharField(max_length=100)),
                ('model_loss', models.CharField(max_length=100)),
                ('model_optimizer', models.CharField(max_length=100)),
                ('epoch', models.IntegerField(max_length=100)),
                ('batch_size', models.IntegerField(max_length=100)),
                ('days', models.IntegerField(max_length=100)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
