# Generated by Django 3.0.5 on 2020-11-15 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('model_training', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companymodeldtls',
            name='batch_size',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='companymodeldtls',
            name='days',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='companymodeldtls',
            name='epoch',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='companymodeldtls',
            name='file_path',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='companymodeldtls',
            name='model_loss',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='companymodeldtls',
            name='model_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='companymodeldtls',
            name='model_optimizer',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
