# Generated by Django 3.0.5 on 2020-11-15 17:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('model_training', '0002_auto_20201115_1604'),
    ]

    operations = [
        migrations.AddField(
            model_name='companymodeldtls',
            name='model_summary',
            field=models.TextField(null=True),
        ),
        migrations.CreateModel(
            name='CompanyModelDtlsHstry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_loss', models.CharField(max_length=100, null=True)),
                ('model_optimizer', models.CharField(max_length=100, null=True)),
                ('epoch', models.IntegerField(null=True)),
                ('batch_size', models.IntegerField(null=True)),
                ('days', models.IntegerField(null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='model_training.CompanyModelDtls')),
            ],
        ),
    ]
