# Generated by Django 3.0.5 on 2020-11-21 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('model_training', '0003_auto_20201115_1745'),
    ]

    operations = [
        migrations.AddField(
            model_name='companymodeldtls',
            name='is_trained',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='companymodeldtls',
            name='trained_on',
            field=models.DateTimeField(null=True),
        ),
    ]
